SMS/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main_app.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = 'Student Management System'                    # default: "Django Administration"
# admin.site.index_title = 'Features area'                 # default: "Site administration"
admin.site.site_title = 'SMS Admin' # default: "Django site admin"

main_app/urls.py
from django.urls import path, include
from . import views
from . import student_views

app_name = "main_app"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.logInUser, name="logInUser"),
    path("logout", views.logOutUser, name="logOutUser"),
    path("contact", views.contact, name="contact"),
    path("services", views.services, name="services"),
    # urls for student views
    path("menu/", views.menu, name="menu"),
    path(
        "student/show_teachers",
        student_views.show_teachers,
        name="student_show_teachers",
    ),
    path(
        "student/show_classmates",
        student_views.show_classmates,
        name="student_show_classmates",
    ),
    path(
        "student/show_attendance",
        student_views.show_attendance,
        name="student_show_attendance",
    ),
    path(
        "student/show_notices",
        student_views.show_notices,
        name="student_show_notices",
    ),
    path(
        "student/show_feedbacks",
        student_views.show_feedbacks,
        name="student_show_feedbacks",
    ),
]

main_app/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.db import models
from django.utils import timezone
from django.dispatch import receiver
from django.db.models.signals import post_save


class CustomUserManager(UserManager):
    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("You have not provided a valid e-mail address")

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)

        user.save(using=self._db)

        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        return self._create_user(email, password, **extra_fields)


class CustomUser(PermissionsMixin, AbstractBaseUser):
    GENDER_CHOICES = [("M", "Male"), ("F", "Female")]
    USER_TYPE_CHOICES = [("1", "Admin"), ("2", "Teacher"), ("3", "Student")]

    username = None
    email = models.EmailField(max_length=255, unique=True, blank=True)
    first_name = models.CharField(max_length=255, blank=True, default="")
    last_name = models.CharField(max_length=255, blank=True, default="")

    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    date_joined = models.DateTimeField(default=timezone.now, blank=True)
    last_login = models.DateTimeField(blank=True, null=True)

    gender = models.CharField(
        max_length=1, blank=True, default="M", choices=GENDER_CHOICES
    )
    user_type = models.CharField(
        max_length=1, blank=True, default="3", choices=USER_TYPE_CHOICES
    )
    updated_at = models.DateTimeField(default=timezone.now, blank=True)
    profile_pic = models.ImageField(
        upload_to="media/profile_pics", null=True, blank=True
    )

    objects = CustomUserManager()

    USERNAME_FIELD = "email"
    EMAIL_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"

    def __str__(self):
        return self.email

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"


class Session(models.Model):
    start_year = models.DateField()
    end_year = models.DateField()

    def __str__(self):
        return "From " + str(self.start_year) + " to " + str(self.end_year)


class Admin(models.Model):
    admin = models.OneToOneField(
        CustomUser, on_delete=models.CASCADE, related_name="admin"
    )


class Course(models.Model):
    name = models.CharField(max_length=120)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Student(models.Model):
    admin = models.OneToOneField(
        CustomUser, on_delete=models.CASCADE, related_name="student"
    )
    course = models.ForeignKey(
        Course,
        on_delete=models.DO_NOTHING,
        null=True,
        blank=False,
        related_name="students",
    )
    session = models.ForeignKey(Session, on_delete=models.DO_NOTHING, null=True)
    address = models.TextField(blank=True, null=True)
    dob = models.DateField(blank=True, null=True)
    father_name = models.CharField(max_length=120, blank=True, null=True)
    mother_name = models.CharField(max_length=120, blank=True, null=True)
    parents_num = models.CharField(max_length=20, blank=True, null=True)

    def __str__(self):
        return self.admin.last_name + ", " + self.admin.first_name


class Staff(models.Model):
    course = models.ForeignKey(
        Course, on_delete=models.DO_NOTHING, null=True, blank=False
    )
    admin = models.OneToOneField(
        CustomUser, on_delete=models.CASCADE, related_name="staff"
    )

    def __str__(self):
        return self.admin.email


class Subject(models.Model):
    name = models.CharField(max_length=120)
    staff = models.ForeignKey(Staff, on_delete=models.CASCADE, related_name="subjects")
    course = models.ForeignKey(
        Course, on_delete=models.CASCADE, related_name="subjects"
    )
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Attendance(models.Model):
    session = models.ForeignKey(Session, on_delete=models.DO_NOTHING)
    subject = models.ForeignKey(Subject, on_delete=models.DO_NOTHING)
    date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.subject.name + " - " + str(self.date)


class AttendanceReport(models.Model):
    student = models.ForeignKey(Student, on_delete=models.DO_NOTHING)
    attendance = models.ForeignKey(Attendance, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f"{self.student.admin.full_name} - {self.attendance.subject.name} - {self.attendance.date}"


class LeaveReportStudent(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    date = models.CharField(max_length=60)
    message = models.TextField()
    status = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class LeaveReportStaff(models.Model):
    staff = models.ForeignKey(Staff, on_delete=models.CASCADE)
    date = models.CharField(max_length=60)
    message = models.TextField()
    status = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class FeedbackStudent(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    feedback = models.TextField()
    reply = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.student.admin.full_name + " - " + str(self.created_at.date())


class FeedbackStaff(models.Model):
    staff = models.ForeignKey(Staff, on_delete=models.CASCADE)
    feedback = models.TextField()
    reply = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class NotificationStaff(models.Model):
    staff = models.ForeignKey(Staff, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.staff.admin.full_name + " - " + self.message[:50]


class NotificationStudent(models.Model):
    STATUS_CHOICES = [("1", "Urgent"), ("0", "General")]
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1, default="0", choices=STATUS_CHOICES)

    def __str__(self):
        return self.student.admin.full_name + " - " + self.message[:50]


class StudentResult(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    test = models.FloatField(default=0)
    exam = models.FloatField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


# @receiver(post_save, sender=CustomUser)
# def create_user_profile(sender, instance, created, **kwargs):
#     if created:
#         if instance.user_type == "1":
#             Admin.objects.create(admin=instance)
#         elif instance.user_type == "2":
#             Staff.objects.create(admin=instance)
#         elif instance.user_type == "3":
#             Student.objects.create(admin=instance)


# @receiver(post_save, sender=CustomUser)
# def save_user_profile(sender, instance, **kwargs):
#     if instance.user_type == "1":
#         instance.admin.save()
#     elif instance.user_type == "2":
#         instance.staff.save()  # Access the related Staff instance through the 'staff' attribute
#     elif instance.user_type == "3":
#         instance.student.save()

main_app/forms.py
from django import forms
from .models import Student, Course, Subject, CustomUser


class SubjectSelectionForm(forms.Form):
    subjects = forms.ModelChoiceField(queryset=None)

    def __init__(self, student: Student, *args, **kwargs):
        super().__init__(*args, **kwargs)
        subjects_queryset = Subject.objects.filter(course=student.course.id)
        self.fields["subjects"].queryset = subjects_queryset


class StudentProfileEditForm(forms.ModelForm):
    email = forms.EmailField(
        label="Email",
        required=False,
        widget=forms.EmailInput(
            attrs={"class": "form-control", "value": "new@email.com"}
        ),
    )
    dob = forms.DateField(
        label="Date Of Birth",
        required=False,
        widget=forms.DateInput(attrs={"type": "date", "class": "form-control"}),
    )
    parents_num = forms.CharField(
        label="Parent's Contact",
        required=False,
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )
    gender = forms.ChoiceField(
        label="Gender",
        required=False,
        choices=CustomUser.GENDER_CHOICES,
        widget=forms.Select(attrs={"class": "form-control"}),
    )
    address = forms.CharField(
        label="Address",
        required=False,
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )

    def __init__(self, student: Student, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance = student
        self.fields["email"].initial = (
            student.admin.email
        )  # set saved email as default value in input
        self.fields["dob"].initial = student.dob
        self.fields["parents_num"].initial = student.parents_num
        self.fields["gender"].initial = student.admin.gender
        self.fields["address"].initial = student.address

    def save(self, commit=True):
        """
        Saves the student's profile changes to the database.

        Args:
            commit (bool): If True, saves the changes to the database. Defaults to True.

        Returns:
            Student: The updated student instance.

        """
        student = self.instance
        student.admin.email = self.cleaned_data["email"]  # get submitted email
        student.dob = self.cleaned_data["dob"]  # get submitted dob
        student.parents_num = self.cleaned_data[
            "parents_num"
        ]  # get submitted parents_num
        student.admin.gender = self.cleaned_data["gender"]  # get submitted gender
        student.address = self.cleaned_data["address"]  # get submitted gender
        if commit:
            student.admin.save()  # save email and gender in customuser model
            student.save()  # save dob, address and parents_num in student model
        return student

    class Meta:
        model = Student
        fields = ()

main_app/views.py
from django.shortcuts import render, redirect
from datetime import datetime
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import StudentProfileEditForm
from .student_views import return_current_student


@login_required(login_url="main_app:logInUser")
def index(request):
    return render(request, "main_app/index.html")


@login_required(login_url="main_app:logInUser")
def menu(request):
    return render(request, "main_app/menu.html")


@login_required(login_url="main_app:logInUser")
def contact(request):
    return render(request, "main_app/contact.html")


@login_required(login_url="main_app:logInUser")
def services(request):
    return render(request, "main_app/services.html")


def logInUser(request):
    context = {"today": datetime.today().year}
    if request.user.is_authenticated:
        return redirect("main_app:index")

    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user=user)
            return redirect("main_app:index")
        else:
            return redirect("main_app:logInUser")
    return render(request, "main_app/login.html", context)


def logOutUser(request):
    logout(request)
    return redirect("main_app:logInUser")


@login_required(login_url="main_app:logInUser")
def menu(request):
    user_types = {"1": "Admin", "2": "Staff", "3": "Student"}
    user_type = user_types[str(request.user.user_type)]
    match (request.user.user_type):
        case "3":
            current_student = return_current_student(request)
            form = StudentProfileEditForm(student=current_student)
            if request.method == "POST":
                form = StudentProfileEditForm(
                    student=current_student, data=request.POST
                )
                if form.is_valid():
                    form.save()

            return render(
                request,
                "student_template/home.html",
                context={"user": request.user, "user_type": user_type, "form": form},
            )
        case _:
            return render(request, "main_app/menu.html")

templates/main_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{% block title %}{% endblock title %} | SMS</title>
    <link
      href="{% static 'css/bootstrap.css' %}"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="{% static 'css/bootstrap.min.css' %}"
      rel="stylesheet"
      type="text/css"
    />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.7.1.min.js' %}"></script>
    <link rel="shortcut icon" href="{% static "main_app/img/favicon.ico" %}" type="image/x-icon">
    <!-- For custom css and js for each page-->
     {% block customsheets %}{% endblock customsheets %}

     <!--Fonts for all pages-->
     <style>
      @import url('https://fonts.googleapis.com/css2?family=Poppins&display=swap');

      body {
        font-family: "Poppins", sans-serif;
        font-weight: 400;
        font-size:1rem;
      }
      
      </style>
  </head>
  <body class="bg-dark" data-bs-theme="dark">
    <!-- NAVBAR -->
    <!-- Check if the current page is not 'dashboard' before including the navbar -->
    {% if request.path != '/menu' %}
      {% include "main_app/navbar.html" %}
    {% endif %}
    <!-- CONTENT -->
    {% block content %}{% endblock content %}
  </body>
</html>

templates/main_app/contact.html
{% extends "main_app/base.html" %}
{% block title %}Contact{%endblock title %} {% block content %}
 {% if messages %}
  {% for message in messages %}
  <div
    class="alert alert-{{ message.tags }} alert-dismissible fade show"
    role="alert"
  >
   <p> <strong>{{message}}</strong> for email : {{email}}</p>
    <button
      type="button"
      class="btn-close"
      data-bs-dismiss="alert"
      aria-label="Close"
    ></button>
  </div>
  {% endfor %}
{% endif %}

<div class="d-flex justify-content-center">
  <form class="px-3 w-50 py-2" method="POST" action="main_app:contact">
    {% csrf_token %}
    <div class="mb-3">
      <label for="name" class="form-label">Name</label>
      <input
        type="text"
        class="form-control"
        id="name"
        placeholder="Enter your name"
        name="name"
      />
    </div>
    <div class="mb-3">
      <label for="email" class="form-label">Email address</label>
      <input
        type="email"
        class="form-control"
        id="email"
        aria-describedby="emailHelp"
        name="email"
        placeholder="Enter your email"
      />
    </div>
    <div class="mb-3">
      <label for="phone" class="form-label">Phone Number</label>
      <input
        type="phone"
        class="form-control"
        id="phone"
        name="phone"
        placeholder="Enter your phone number"
      />
    </div>

    <div class="mb-3">
      <label for="exampleFormControlTextarea1" class="form-label"
        >Tell me what you want to say</label
      >
      <textarea
        class="form-control"
        id="desc"
        name="desc"
        placeholder="Enter your query"
        rows="3"
      ></textarea>
    </div>

    <button type="submit" class="btn btn-primary w-100">Submit</button>
  </form>
</div>
{% endblock content %}

templates/main_app/dashboard.html
{% extends "main_app/base.html" %} {% load static %} 
{% block title %}Home{%endblock title %} 

{%block content %}
<div class="d-flex flex-column flex-shrink-0 p-3 text-bg-dark" style="width: 280px;">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
      <span class="fs-4">SMS</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
        <a href="#" class="nav-link active" aria-current="page">
          Dashboard
        </a>
      </li>
      <li>
        <a href="#" class="nav-link text-white">
          Teacher
        </a>
      </li>
      <li>
        <a href="#" class="nav-link text-white">
          Student
        </a>
      </li>
      <li>
        <a href="#" class="nav-link text-white">
          Attendance
        </a>
      </li>
      <li>
        <a href="#" class="nav-link text-white">
          Fee Structure
        </a>
      </li>
      <li>
        <a href="#" class="nav-link text-white">
          Notices
        </a>
      </li>
    </ul>
    <hr>
    <div class="dropdown">
      <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
        <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
        <strong>mdo</strong>
      </a>
      <ul class="dropdown-menu dropdown-menu-dark text-small shadow" style="">
        <li><a class="dropdown-item" href="{% url "main_app:index" %}">Home</a></li>
        <li><a class="dropdown-item" href="{% url "main_app:contact" %}">Contact</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="{% url "main_app:logOutUser" %}">Sign out</a></li>
      </ul>
    </div>
  </div>
{%endblock content%}

templates/main_app/index.html
{% extends "main_app/base.html" %} {% load static %} 
{% block title %}Home{%endblock title %} 
{%block customsheets %}
<link href="{% static 'css/index.css' %}" rel="stylesheet" type="text/css" />
{%endblock customsheets %}

{%block content %}
<main class="px-3 d-flex justify-content-center">
  <div class="w-75 mt-5 d-flex flex-column align-items-center gap-3">
    <h1>Student Management System</h1>
    <p class="lead text-justify">
      Our student management system makes it easy to keep track of all your
      school's student information in one place. With this system, you can
      quickly enroll new students, record attendance, manage grades, and
      communicate with parents. The user-friendly interface allows teachers and
      staff to access important student data whenever they need it. This helps
      the school run more efficiently and allows everyone to focus on supporting
      the students' academic success.
    </p>
    <p class="lead d-flex justify-content-center">
      <a href="#" class="btn btn-lg btn-light fw-bold border-white bg-white"
        >Contact Us</a
      >
    </p>
  </div>
</main>
{% endblock content %}

templates/main_app/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-bs-theme="auto">
  <link
    href="{% static 'css/bootstrap.min.css' %}"
    rel="stylesheet"
    type="text/css"
  />
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  <head>
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, 0.1);
        border: solid rgba(0, 0, 0, 0.15);
        border-width: 1px 0;
        box-shadow: inset 0 0.5em 1.5em rgba(0, 0, 0, 0.1),
          inset 0 0.125em 0.5em rgba(0, 0, 0, 0.15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -0.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }

      .bd-mode-toggle {
        z-index: 1500;
      }

      .bd-mode-toggle .dropdown-menu .active .bi {
        display: block !important;
      }
      html,
      body {
        height: 100%;
      }

      .form-signin {
        max-width: 330px;
        padding: 1rem;
      }

      .form-signin .form-floating:focus-within {
        z-index: 2;
      }

      .form-signin input[type="email"] {
        margin-bottom: -1px;
        border-bottom-right-radius: 0;
        border-bottom-left-radius: 0;
      }

      .form-signin input[type="password"] {
        margin-bottom: 10px;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
      }
    </style>
  </head>
  <body class="d-flex align-items-center py-4 bg-dark" data-bs-theme="dark">
    <main class="form-signin w-100 m-auto">
      <form method="POST" action="{% url 'main_app:logInUser' %}">
        {% csrf_token %}
        <h1 class="h3 mb-3 fw-normal text-center">SMS SignIn Form</h1>

        <div class="form-floating mb-3">
          <input
            type="text"
            class="form-control"
            id="floatingInput"
            placeholder="Enter your username"
            name="username"
          />
          <label for="floatingInput">Username</label>
        </div>
        <div class="form-floating mb-3">
          <input
            type="password"
            name="password"
            class="form-control"
            id="floatingPassword"
            placeholder="Enter your password"
          />
          <label for="floatingPassword">Password</label>
        </div>
        <button class="btn btn-primary w-100 py-2" type="submit">
          Sign in
        </button>
        <p class="mt-5 mb-3 text-body-secondary text-center">
          &copy; {{today}} - SMS Admin
        </p>
      </form>
    </main>
  </body>
</html>

templates/main_app/menu.html
{% extends "main_app/base.html" %} {% load static %} 
{% block title %}Main Menu{%endblock title %} 

{%block content %}
<div class="d-flex">

  <!--SIDEBAR-->
<div class="d-flex flex-column flex-shrink-0 p-3 text-bg-dark" style="width: 280px;">
    
    <hr>
    <ul class="nav nav-pills flex-column">
      <li class="nav-item">
        <a href="{% url "main_app:menu" %}" class="nav-link text-white" >
          Dashboard
        </a>
      </li>
      <li>
        <a href="{% url "main_app:student_show_teachers" %}" class="nav-link text-white">
          Teacher
        </a>
      </li>
      <li>
        <a href="{% url "main_app:student_show_classmates" %}" class="nav-link text-white">
          Student
        </a>
      </li>
      <li>
        <a href="{% url "main_app:student_show_attendance" %}" class="nav-link text-white">
          Attendance
        </a>
      </li>
      <li>
        <a href="{% url "main_app:student_show_notices" %}" class="nav-link text-white">
          Notices
        </a>
      </li>
      <li>
        <a href="{% url "main_app:student_show_feedbacks" %}" class="nav-link text-white">
          Feedback
        </a>
      </li>
    </ul>
    <hr>

      <a href="#" class="d-flex align-items-center text-white text-decoration-none">
        {% if request.user.profile_pic %}
          <img src="{{request.user.profile_pic.url}}" alt="" width="32" height="32" class="rounded-circle me-2">
          {% else %}
          <img src="{% static "main_app/img/ditto.png" %}" alt="" width="32" height="32" class="rounded-circle me-2">

        {% endif %}
        <strong>{{request.user.full_name}}</strong>
      </a>
      
  
  </div>
  <div class="d-flex gap-3 mt-3 flex-column px-3 mx-auto w-50">
  <!-- For menu content for all types of the user-->
{% block menu_content %}{% endblock menu_content %}
  </div>
</div>
{%endblock content%}

templates/main_app/navbar.html
 {% load static %}
 <script src="{% static "js/navbar.js" %}"></script>
 <nav class="navbar navbar-expand-md bg-dark">
  <div class="container-fluid">
    <div class="d-flex justify-content-between w-100">
      <div class="navbar-brand" title="Student Management System">
        Student Management System
      </div>
      <div>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNavAltMarkup"
          aria-controls="navbarNavAltMarkup"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">

        <!--NOTE: This may look bad code but is necessary to highlight the current active page-->
        <a class="nav-link {% if request.resolver_match.view_name == "main_app:index" %}active{% endif %}" href="{% url "main_app:index" %}">Home</a>
        <a class="nav-link {% if request.resolver_match.view_name == "main_app:services" %}active{% endif %}" href="{% url "main_app:services" %}">Services</a>
        <a class="nav-link {% if request.resolver_match.view_name == "main_app:menu" %}active{% endif %}" href="{% url "main_app:menu" %}">Menu</a>
        <a class="nav-link {% if request.resolver_match.view_name == "main_app:contact" %}active{% endif %}" href="{% url "main_app:contact" %}">Contact</a>
        <a class="nav-link {% if request.resolver_match.view_name == "main_app:logOutUser" %}active{% endif %}" href="{% url "main_app:logOutUser" %}">LogOut</a>
      </div>
    </div>
  </div>
</nav> 